#****************************************
# Variables to control MakeFile operation

CXX = g++
CXXFLAGS = -Wall -g

#****************************************
# Targets needed to bring the executable up to date

main: main.o function.o File_IO.o Customer.o List.o
	$(CXX) $(CXXFLAGS) -o main main.o function.o File_IO.o Customer.o List.o

main.o: main.cpp function.h File_IO.h Customer.h List.h
	$(CXX)(CXXFLAGS) -c main.cpp

funtion.o: function.h Customer.h List.h

File_IO.o: File_IO.h Customer.h List.h

Customer.o: Customer.h List.h

List.o: List.h

.PHONEY: clean

clean: -rm main main.o function.o File_IO.o Customer.o List.o
